"""Add created_at to Order table

Revision ID: 13721cec1b32
Revises: 6442beb192ec
Create Date: 2024-10-22 15:06:06.311263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13721cec1b32'
down_revision = '6442beb192ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('order_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['customer_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_ibfk_3', 'user', ['user_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
